version: '3.4'

services:
  newza:
    image: newza
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8100:8100"
    command: sh -c 'npm install; ionic serve --external'